spring.application.name=spring-gift
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1;CASE_INSENSITIVE_IDENTIFIERS=TRUE
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.mode=always
jwt.secret.key=Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true

kakao.client-id=af6e80383ad6bbfe5fe26ed030845191
kakao.redirect-uri=http://localhost:8080/oauth/kakao/callback
kakao.token-url=https://kauth.kakao.com/oauth/token
kakao.send-message-url=https://kapi.kakao.com/v2/api/talk/memo/default/send
kakao.user-info-url=https://kapi.kakao.com/v2/user/me
kakao.redirect-message-web-url=http://localhost:8080/orders
kakao.redirect-message-mobile-url=http://localhost:8080/orders